services:

  web:
    build: .
    # command: gunicorn travulas.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --workers 3
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/code



