name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.7.0"
    - name: View poetry --help
      run: poetry --help
    - name: Installing poetry dependencies
      run: poetry install
    - name: Test with manage.py test
      run: |
        export CHANNELS_REDIS_HOST="127.0.0.1"
        poetry run pytest -v 
